packages:
  - "packages/*"
  - "tests/*"
  - "extension/*"
  - "extension/toolkit/*"
  - "extension/toolkit/features/*"
  - "extension/toolkit/features/widgets/*"
  - "extension/toolkit/features/transactions/*"
  - "extension/toolkit/features/dashboard/*"
  - "extension/toolkit/features/nav-bar/*"
  - "extension/toolkit/features/budget/*"
